version: '3'
services: 
    redis-shaobing-replica-1:
        image: redis:5
        container_name: redis-shaobing-replica-1
        volumes:
            - ./redis-slave-1.conf:/usr/local/etc/redis/redis.conf
            - ./data/data-slave-1:/data
            # - ./logs/redis-slave1.log:/var/log/redis/redis.log
        ports: 
            - "20001:6379"
        networks:
            redis-replica-networks:
                ipv4_address: 192.200.200.201
        command: redis-server /usr/local/etc/redis/redis.conf
        tty: true
    
    redis-shaobing-replica-2:
        image: redis:5
        container_name: redis-shaobing-replica-2
        volumes:
            - ./redis-slave-2.conf:/usr/local/etc/redis/redis.conf
            - ./data/data-slave-2:/data
            # - ./logs/redis-slave2.log:/var/log/redis/redis.log
        ports: 
            - "20002:6379"
        networks:
            redis-replica-networks:
                ipv4_address: 192.200.200.202
        command: redis-server /usr/local/etc/redis/redis.conf
    
    redis-shaobing-replica-3:
        image: redis:5
        container_name: redis-shaobing-replica-3
        volumes:
            - ./redis-slave-3.conf:/usr/local/etc/redis/redis.conf
            - ./data/data-slave-3:/data
            # - ./logs/redis-slave3.log:/var/log/redis/redis.log
        ports: 
            - "20003:6379"
        networks:
            redis-replica-networks:
                ipv4_address: 192.200.200.203
        command: redis-server /usr/local/etc/redis/redis.conf
    
    redis-shaobing-sentinel-1:
        depends_on:
            - redis-shaobing-replica-1
            - redis-shaobing-replica-2
            - redis-shaobing-replica-3
        image: redis:5
        container_name: redis-shaobing-sentinel-1
        volumes:
            - ./sentinel-1.conf:/usr/local/etc/redis/sentinel.conf
            # - ./logs/redis-slave2.log:/var/log/redis/redis.log
        ports: 
            - "20004:26379"
        networks:
            redis-replica-networks:
                ipv4_address: 192.200.200.204
        command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    
    redis-shaobing-sentinel-2:
        depends_on:
            - redis-shaobing-replica-1
            - redis-shaobing-replica-2
            - redis-shaobing-replica-3
        image: redis:5
        container_name: redis-shaobing-sentinel-2
        volumes:
            - ./sentinel-2.conf:/usr/local/etc/redis/sentinel.conf
            # - ./logs/redis-slave2.log:/var/log/redis/redis.log
        ports: 
            - "20005:26379"
        networks:
            redis-replica-networks:
                ipv4_address: 192.200.200.205
        command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    
    redis-shaobing-sentinel-3:
        depends_on:
            - redis-shaobing-replica-1
            - redis-shaobing-replica-2
            - redis-shaobing-replica-3
        image: redis:5
        container_name: redis-shaobing-sentinel-3
        volumes:
            - ./sentinel-3.conf:/usr/local/etc/redis/sentinel.conf
            # - ./logs/redis-slave2.log:/var/log/redis/redis.log
        ports: 
            - "20006:26379"
        networks:
            redis-replica-networks:
                ipv4_address: 192.200.200.206
        command: redis-sentinel /usr/local/etc/redis/sentinel.conf

networks:
    redis-replica-networks:
        ipam:
            config:
                - subnet: 192.200.200.0/16
